#!/bin/bash

  

for ((i=1;i<=45;i++)); 
do 
   PAGE="$i"
   URL="https://nemo.intello.io/p/saas-directory?page=$PAGE"
   wget "$URL" -O - >> ~/pbindustries/misoWork/scraping/output.json
   echo " - Page $i saved - "
done
